# Generated by Django 4.2.7 on 2025-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparql_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JsonData',
            new_name='Data',
        ),
    ]
