# Generated by Django 4.2.7 on 2025-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparql_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='xmlLang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
