# Generated by Django 4.2.7 on 2025-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
